In [6]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/IDS

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/IDS

In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [2]:
df_2021 = pd.read_csv('origin/2021.csv')
df_2020 = pd.read_csv('origin/2020.csv')
df_2019 = pd.read_csv('origin/2019.csv')
df_2018 = pd.read_csv('origin/2018.csv')
df_2017 = pd.read_csv('origin/2017.csv')
df_2016 = pd.read_csv('origin/2016.csv')
df_2015 = pd.read_csv('origin/2015.csv')
df_health = pd.read_csv('origin/mental_health_dataset.csv')

In [7]:
country_list = ['United States', 'United Kingdom', 'Australia', 'India', 'Germany', 'Canada']
columns_to_normalize = ['GDP', 'Healthy life expectancy', 'Corruption']

scaler = MinMaxScaler()

def process_yearly_data(df, rename_dict, year):
    df = df[list(rename_dict.keys())].rename(columns=rename_dict)
    df[columns_to_normalize] = scaler.fit_transform(df[columns_to_normalize])  # normalize selected columns
    df['Year'] = year
    return df

# define the rename dictionaries
df_2021 = process_yearly_data(
    df_2021,
    {
      'Country name': 'Country',
      'Ladder score': 'Happiness score',
      'Logged GDP per capita': 'GDP',
      'Perceptions of corruption': 'Corruption',
      'Healthy life expectancy': 'Healthy life expectancy'
    },
    2021
)
df_2020 = process_yearly_data(
    df_2020,
    {
      'Country name': 'Country',
      'Ladder score': 'Happiness score',
      'Logged GDP per capita': 'GDP',
      'Perceptions of corruption': 'Corruption',
      'Healthy life expectancy': 'Healthy life expectancy'
    },
    2020
)
df_2019 = process_yearly_data(
    df_2019,
    {
      'Country or region': 'Country',
      'Score': 'Happiness score',
      'Perceptions of corruption': 'Corruption',
      'GDP per capita': 'GDP',
      'Healthy life expectancy': 'Healthy life expectancy'
    },
    2019
)
df_2018 = process_yearly_data(
    df_2018,
    {
      'Country or region': 'Country',
      'Score': 'Happiness score',
      'Perceptions of corruption': 'Corruption',
      'GDP per capita': 'GDP',
      'Healthy life expectancy': 'Healthy life expectancy'
    },
    2018
)
df_2017 = process_yearly_data(
    df_2017,
    {
      'Happiness.Score': 'Happiness score',
      'Economy..GDP.per.Capita.': 'GDP',
      'Health..Life.Expectancy.': 'Healthy life expectancy',
      'Trust..Government.Corruption.': 'Corruption'
    },
    2017
)
df_2016 = process_yearly_data(
    df_2016,
    {
      'Happiness Score': 'Happiness score',
      'Economy (GDP per Capita)': 'GDP',
      'Health (Life Expectancy)': 'Healthy life expectancy',
      'Trust (Government Corruption)': 'Corruption'
    },
    2016
)

# concatenate all df
df_all_years = pd.concat([df_2021, df_2020, df_2019, df_2018, df_2017, df_2016], ignore_index=True)

df_all_years = df_all_years[df_all_years['Country'].isin(country_list)]
df_all_years['Country'] = df_all_years['Country'].replace({
    'United States': 'USA',
    'United Kingdom': 'UK',
})

df_country = df_all_years.groupby('Country').mean().drop(columns=['Year'])

In [8]:
df_country

           Happiness score       GDP  Corruption  Healthy life expectancy
Country
Australia         7.226450  0.784249    0.522721                 0.895750
Canada            7.235275  0.779596    0.511396                 0.892108
Germany           7.045200  0.788854    0.514628                 0.849735
India             3.899325  0.422684    0.500141                 0.472043
UK                7.118125  0.756495    0.406988                 0.859048
USA               6.917150  0.821891    0.501688                 0.746160

In [9]:
df_health = df_health.drop(columns=['Severity']).rename(columns={'Mental_Health_Condition': 'Mental_Health_Issue'})
df_final = df_health.merge(df_country, on='Country', how='left')

In [10]:
df_final

,User_ID,Age,Gender,Occupation,Country,Mental_Health_Issue,Consultation_History,Stress_Level,Sleep_Hours,Work_Hours,Physical_Activity_Hours,Happiness score,GDP,Corruption,Healthy life expectancy
0,1,36,Non-binary,Sales,Canada,No,Yes,Medium,7.1,46,5,7.235275,0.779596,0.511396,0.892108
1,2,34,Female,Education,UK,Yes,No,Low,7.5,47,8,7.118125,0.756495,0.406988,0.859048
2,3,65,Non-binary,Sales,USA,Yes,No,Low,8.4,58,10,6.917150,0.821891,0.501688,0.746160
3,4,34,Male,Other,Australia,No,No,Medium,9.8,30,2,7.226450,0.784249,0.522721,0.895750
4,5,22,Female,Healthcare,Canada,Yes,No,Medium,4.9,62,5,7.235275,0.779596,0.511396,0.892108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,46,Non-binary,Other,Germany,No,Yes,Low,9.3,50,0,7.045200,0.788854,0.514628,0.849735
996,997,31,Male,Sales,Canada,No,No,High,4.5,37,6,7.235275,0.779596,0.511396,0.892108
997,998,33,Female,IT,Germany,No,Yes,Medium,9.7,73,10,7.045200,0.788854,0.514628,0.849735
998,999,42,Female,Finance,Australia,Yes,No,Medium,6.5,79,8,7.226450,0.784249,0.522721,0.895750
999,1000,43,Prefer not to say,Sales,Germany,No,Yes,Low,6.0,61,7,7.045200,0.788854,0.514628,0.849735

In [12]:
df_final.to_csv('processed/mental_health_country.csv', index=False)
df_country.to_csv('processed/country_mean.csv', index=False)
df_all_years.to_csv('processed/country_all_years.csv', index=False)